### PR TITLE
Geoffdavis92/react

### PR DESCRIPTION
**Pull request by geoffdavis92**
Added an **Error Handling**/`componentDidCatch` entry for React lifecycle methods; added links to lifecycle method documentation.

Updates #27

### CODE REVIEW

**Comment by feimosi** [comment]
Looks good, just fix the merge conflicts please.

**Comment by feimosi** [comment]
Any update here? :slightly_smiling_face:

**Comment by geoffdavis92** [comment]
@feimosi Sorry, been out of town. Conflict resolved.

**Comment by feimosi** [comment]
No problem, thanks!

**Pull request merged**
